### ISSUE TITLE
cannot use testSize (type uint64) as type int64

### ISSUE THREAD

**Issue by zeroxd0d0e0a0d0b0e0e0f** [malware-unicorn/GoPEInjection#1]
```
go build .

# peinjection
.\main.go:309:34: cannot use testSize (type uint64) as type int64 in argument to CreateNewSection
.\main.go:315:43: cannot use testSize (type uint64) as type uint32 in argument to MapViewOfSection
.\main.go:323:44: cannot use testSize (type uint64) as type uint32 in argument to MapViewOfSection
```

Wrong type?

**Comment by scaery** [comment]
not foxed yet ;)

sure, then your fix also needs int64(testSize), likewise as declared in the definition of CreateNewSection

**Comment by zeroxd0d0e0a0d0b0e0e0f** [comment]
rewriting to uint32 solves 2 of 3 errors

your fix also needs int64(testSize), likewise as declared in the definition of CreateNewSection

**Comment by malware-unicorn** [comment]
Let me know if you still see errors @zeroxd0d0e0a0d0b0e0e0f  ✌️
